from selenium.webdriver.common.by import By


class LoginPage:
    loading = (By.CLASS_NAME,"css-1ji7omv-MuiBackdrop-root")
    loginBtn = (By.XPATH, "//button[@class='loginBtn']")
    username = (By.XPATH, "//input[@type='email']")
    password = (By.XPATH, "//input[@type='password']")
    NextBtn = (By.XPATH, "//input[@type='submit']")
    SignIn = (By.XPATH, "//input[@value='Sign in']")
    BackBtn = (By.ID, "idBtn_Back")
    V_track = (By.XPATH, "//span[text()='Track']/../../..")
    clientTab = (By.XPATH, "//div[text()='Client Admin']/..")
    body = (By.ID, "root")
    addBtn = (By.CSS_SELECTOR,".addBtn .btnText")
    clientName = (By.CSS_SELECTOR,'#outlined-required[type="text"]')
    clientLocation = (By.CSS_SELECTOR,'[aria-labelledby="label-for-location outlined-select-currency"]')
    currency = (By.CSS_SELECTOR,'[aria-labelledby="label-for-currency outlined-select-currency"]')
    MSAStartDate = (By.XPATH,"(//tr[@id='new_row']/td/div/div/input[@type='tel'])[1]")
    MSAEndDate = (By.XPATH,"(//tr[@id='new_row']/td/div/div/input[@type='tel'])[2]")
    businessOwner = (By.CSS_SELECTOR,'[aria-labelledby="label-for-businessOwner outlined-select-currency"]')
    clientLocationLi = (By.XPATH,'//li[text()="India"]')
    inr = (By.XPATH,'//li[text()="Indian Rupee"]')
    veersaDummyUser = (By.XPATH,'//li[text()="Veersa Technologies (noreply@veersatech.com)"]')
    paymentTerms = (By.CSS_SELECTOR,'[id="outlined-required"][type="number"]')
    deliveryOfficer = (By.CSS_SELECTOR,'[aria-labelledby="label-for-deliveryOfficer outlined-select-currency"]')
    addIcon = (By.XPATH,"(//tr[@id='new_row']/td/div/img)[1]")
